[project]
name        = "ps-plugin-sdk"
description = ""
requires-python = ">=3.10,<3.14"
dynamic = ["version"]

[tool.poetry.dependencies]
poetry = "^2.2.1"
toml = "^0.10.2"
pydantic = "^2.12.5"

[tool.poetry]
packages = [ { include = "ps/plugin/sdk", from = "src" } ]

[tool.ps-plugin]
host-project = ".."

[build-system]
requires    = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"