[project]
name        = "ps-plugin-module-check"
description = ""
requires-python = ">=3.10,<4.0"
dynamic = ["version"]

[tool.poetry.dependencies]
poetry = "^2.2.1"
toml = "^0.10.2"
pydantic = "^2.12.5"

[project.entry-points."ps.module"]
module_entry = "ps.plugin.module.check"

[tool.poetry.group.ps.dependencies]
ps-plugin-sdk = { path = "../../sdk", develop = true }

[tool.poetry]
packages = [ { include = "ps/plugin/module/check", from = "src" } ]
version = "0.0.0"

[tool.ps-plugin]
enabled = true
monorepo = "child"

[build-system]
requires    = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"