[project]
name = "ps-poetry"
description = ""
requires-python = ">=3.10,<4.0"
dynamic = ["dependencies", "version"]

[tool.poetry]
packages = [
    { include = "src", from = "plugin" },
    { include = "experiments", from = "." },
]
version = "0.0.0"

[tool.poetry.dependencies]
poetry = "^2.2.1"
toml = "^0.10.2"

[tool.poetry.group.dev.dependencies]
"ruff" = "^0.14.9"
pytest = "^9.0.2"
pytest-cov = "^7.0.0"
autopep8 = "^2.3.2"
pytest-asyncio = "^1.3.0"

[tool.poetry.requires-plugins]
ps-plugin-core = {path = "plugin/dist/ps_plugin_core-0.0.0-py3-none-any.whl"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylance]
typeCheckingMode = "standard"